controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 1.0 #0.5
  min_vel_x: 0.1 #0.01
  max_vel_theta: 1.5 #1.2

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 1.0
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  sim_time: 0.5

  vx_samples: 10.0
  vtheta_samples: 10.0

  pdist_scale: 4.0 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.1

  holonomic_robot: false
